apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: http-go
  name: http-go
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      app: http-go
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: http-go
    spec:
      containers:
      - image: 445567110488.dkr.ecr.us-east-1.amazonaws.com/product-app:2024-10-26.10.42.40
        name: http-go
        resources: {}
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            #httpHeaders:
            #- name: Custom-Header
              #value: Awesome
          initialDelaySeconds: 3
          periodSeconds: 2
          failureThreshold: 1
status: {}
