---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: http-go
  name: http-go
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: http-go
  type: LoadBalancer
status:
  loadBalancer: {}
